### ISSUE TITLE
1.1.1 develop: is client actually installed or is that just a symlink?

### ISSUE THREAD

**Issue by ghost** [CounterpartyXCP/federatednode#216]
https://github.com/CounterpartyXCP/federatednode_build/blob/develop/run.py#L466
And no config file is generated. 
1. Is that on purpose? If yes, we `README` should inform users to create their own client config file.
2. What happens if users try to install or update the client via pip? What would be the right way to update it?
##

**Comment by robby-dermody** [comment]
hmm, the counterparty-cli setup script should create a -cli config file if none exists (see https://github.com/CounterpartyXCP/counterparty-cli/blob/master/setup.py#L28), but, I reran the setup rebuild process, after removing my counterparty `client.conf` file, and none was created.

paging @ouziel-slama ...any input here? wouldn't this client.conf file be created automatically during the -cli install process if none existed?

**Comment by ouziel-slama** [comment]
@robby-dermody, yep the file should be automatically created in the default location.

**Comment by rippler** [comment]
For now I create it manually, but that may be confusing to some users because 'rpc-user' does not appear in `server.[testnet.]conf`.

**Comment by unsystemizer** [comment]
I'll continue here because this is the same problem (no client), although now in Docker.

I assume this is correct: 
```
$ fednode exec counterparty-testnet counterparty-client getinfo
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-client')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/counterparty-cli/counterpartycli/client.py", line 71, in main
    add_config_arguments(parser, CONFIG_ARGS, 'client.conf')
  File "/counterparty-cli/counterpartycli/util.py", line 178, in add_config_arguments
    with codecs.open(config_file, 'r+b') as fp:
  File "/usr/lib/python3.5/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/counterparty/client.conf'
```

For those who come across this problem, this is how I get around it with FedNode on testnet:

* Start bitcoin-testnet and counterparty-testnet
* `fednode exec counterparty-testnet` to enter the CP testnet container 
 * Create a config file for the client (/root/.config/counterparty/client.testnet.conf). Make sure you point it to the right host(s). For example (below) I point it to one IP for Bitcon Core (testnet), and for counterparty server (testnet) I use `localhost` because it's in the same container. Maybe in "standard" FedNode it's OK to point the both at `localhost`. (If unsure, check the docs to find out - https://github.com/CounterpartyXCP/Documentation/blob/master/Installation/federated_node.md#administration). Don't mix up testnet and mainnet config file names, etc.!
 * Exit the container
* Now the client works (example below) as long as you don't restart the containers (I think, I haven't tried but if the installed config file disappears maybe you can add it again).

### Inside of counterparty-testnet
```
root@ubuntu-cp-t:/# cat /root/.config/counterparty/client.testnet.conf
[Default]

counterparty-rpc-connect = localhost
counterparty-rpc-user = rpc
counterparty-rpc-password = 1234
wallet-name = bitcoincore
wallet-connect = 192.168.3.203
wallet-user = rpc
wallet-password = 1234
requests-timeout = 300
testnet = 1

root@ubuntu-cp-t:/# exit
exit

```

#### On the host, I can use counterparty-client inside of `counterparty-testnet` container. 

```
user@ubuntu:~$ fednode exec counterparty-testnet counterparty-client --config /root/.config/counterparty/client.testnet.conf getinfo
[2017-01-20 14:33:44][INFO] Running v1.1.2 of counterparty-client.
Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli', 'console_scripts', 'counterparty-client')()
  File "/counterparty-cli/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/counterparty-cli/counterpartycli/client.py", line 247, in main
    view = console.get_view(args.action, args)
  File "/counterparty-cli/counterpartycli/console.py", line 16, in get_view
    return util.api('get_running_info')
  File "/counterparty-cli/counterpartycli/util.py", line 92, in api
    return rpc(config.COUNTERPARTY_RPC, method, params=params, ssl_verify=config.COUNTERPARTY_RPC_SSL_VERIFY)
  File "/counterparty-cli/counterpartycli/util.py", line 82, in rpc
    raise RPCError(str(response.status_code) + ' ' + response.reason + ' ' + response.text)
counterpartycli.util.RPCError: 503 SERVICE UNAVAILABLE {"data": "Counterparty database is behind backend.", "message": "Server error", "code": -32000}
```

Another workaround is to simply install the client on the host (and point it to the bitcoin and counterparty containers, respectively).

**Comment by unsystemizer** [comment]
@deweller this can be closed, counterparty-cli gets installed in latest release (maybe before that as well)
