### ISSUE TITLE
fednode tail counterwallet error

### ISSUE THREAD

**Issue by ecxotarama** [CounterpartyXCP/federatednode#292]
Hello,
I trying setup an federatednode to exchange, however  when i running  "fednode tail counterwallet" then it's a bug:
![counterparty](https://cloud.githubusercontent.com/assets/22535993/19019116/54294474-88a4-11e6-8296-a59cf0de5b7b.png)

How doing fix it ? Thanks.
##

**Comment by unsystemizer** [comment]
Maybe you can download jquery-timego 1.4.0 (https://github.com/rmm5t/jquery-timeago/releases) and decompress it to that location (and chown/chmod as other .js files in Counterwallet), but if this is in Docker it could be a bit complicated.

Ideally this (wrong link?) should be fixed in the Counterwallet source code. 

Are you sure you didn't have any connection timeout when installing and downloading fednode?
