### ISSUE TITLE
Error: No such volume: federatednode_counterparty-data

### ISSUE THREAD

**Issue by ecxotarama** [CounterpartyXCP/federatednode#293]
When i runing fednode install full develop then error : 
Error: No such volume: federatednode_bitcoin-data
Error: No such volume: federatednode_counterparty-data
Error: No such volume: federatednode_counterblock-data
Error: No such volume: federatednode_mongodb-data
Error: No such volume: federatednode_armory-data
How i can fixed it ? 
##

**Comment by unsystemizer** [comment]
When you installed, you didn't complete installation. Or you lost data, or you messed up your config files. 

The easiest way is to uninstall (sudo fednode uninstall) and re-install. Or rebuild. 
Since you've already downloaded the files, the rebuilding shouldn't take long (but for the blockchain to be downloaded, will). 
You can see here (http://counterparty.io/docs/federated_node/) under "Rebuilding a service container" you can rebuild one, or all.
