### ISSUE TITLE
Revert the auto-restart option

### ISSUE THREAD

**Issue by jotapea** [CounterpartyXCP/federatednode#340]
Auto-restart for the fednode software should be an advanced configuration, decided by the node operator. The current behavior puts new fednode users in a bad position of not understanding why their nodes don't finish syncing.

This already happened to me, wasting time and money because of this (https://github.com/CounterpartyXCP/counterparty-lib/pull/1212#issuecomment-1311918934).

The command could be "kept" as a comment to easily enable it if someone wishes to use it.

**Comment by jotapea** [comment]
Talking about this: https://github.com/CounterpartyXCP/federatednode/issues/332

**Comment by jotapea** [comment]
I disagree. Auto-restart goes against finding bugs and onboarding new nodes. Advanced node operators can always have the option to set the auto-restart, new node operators should NOT be added this kind of responsibility. I wasted weeks because of this.

**Comment by jdogresorg** [comment]
@jotapea to clarify, you "wasted weeks" on this because you demanded you wanted to do a full parse even though it was explained to you multiple times that a full-parse would fail until Javier and I had the fullparse/reparse fixes in place. You continued on with your full parse, and inevitably the full parse failed, and this auto-restart option restarted the failing parse... THAT is why you "wasted weeks", not because you were running the fednode in a way which normal users would be, and you were specifically warned that what you were doing would be a waste of time until the fullparse/reparse fix was in place.

Lets try to be honest here and not paint an unrealistic scene where lots of CPU resources are being wasted for the normal users.

**Comment by jotapea** [comment]
Read here: https://github.com/CounterpartyXCP/counterparty-lib/pull/1212#issuecomment-1307442387

I also tried to have a v9.60 node.

Now, lets get back to the argument. What do you think of improving the experience to optimize the onboarding new nodes?

**Comment by jotapea** [comment]
Can you focus on the issue? I've been knowing you and I've learned that you tend to do this, talk about separate situations that are hard to prove for external readers.

And I'm not arguing here and I'm fine if you don't want to talk about it. Lets keep the issue open for other people to comment...

**Comment by jdogresorg** [comment]
I am focused on the issue at hand, and have explained why the change was made.

I would prefer to keep this a technical conversation, however when you make inaccurate statements about how an option will "waste weeks", I feel that it is important to clarify the actual situation, since the picture your painting is inaccurate. 

Yes, this issue will stay open for a while to allow others to weigh in.

**Comment by jotapea** [comment]
Incredible how you continue talking like if you are me. You know the truth, I was explained about the looping behavior hours before I made the GitHub comment. So, the weeks did pass.

**Comment by jotapea** [comment]
Closing this in favor of https://github.com/CounterpartyXCP/counterparty-lib/issues/1342.
